cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "//libnumber:numberCreator",
        "//libnumber:numberHelper",
        "//libnumber/containers:numberContainer",
    ],
    linkstatic = False,
)
